print("Starting...")
print("Initial position: 0, +0.25")
mi_selectgroup(1)
mi_analyze()
mi_loadsolution()
mo_groupselectblock(1)
Fx = mo_blockintegral(18)
Fy = mo_blockintegral(19)
T = mo_blockintegral(22)
mo_close()
print("Results: Fx: ",Fx, " Fy: ", Fy, " torque: ",T)

print("Moving to 0, 0")
mi_selectgroup(1)
mi_movetranslate(0, -0.25, 4)
mi_analyze()
mi_loadsolution()
mo_groupselectblock(1)
Fx = mo_blockintegral(18)
Fy = mo_blockintegral(19)
T = mo_blockintegral(22)
mo_close()
print("Results: Fx: ",Fx, " Fy: ", Fy, " torque: ",T)

print("Moving to 0, -0.25")
mi_selectgroup(1)
mi_movetranslate(0, -0.25, 4)
mi_analyze()
mi_loadsolution()
mo_groupselectblock(1)
Fx = mo_blockintegral(18)
Fy = mo_blockintegral(19)
T = mo_blockintegral(22)
mo_close()
print("Results: Fx: ",Fx, " Fy: ", Fy, " torque: ",T)

print("Moving to -0.25, +0.25")
mi_selectgroup(1)
mi_movetranslate(-0.25, 0.5, 4)
mi_analyze()
mi_loadsolution()
mo_groupselectblock(1)
Fx = mo_blockintegral(18)
Fy = mo_blockintegral(19)
T = mo_blockintegral(22)
mo_close()
print("Results: Fx: ",Fx, " Fy: ", Fy, " torque: ",T)

print("Moving to -0.25, 0")
mi_selectgroup(1)
mi_movetranslate(0, -0.25, 4)
mi_analyze()
mi_loadsolution()
mo_groupselectblock(1)
Fx = mo_blockintegral(18)
Fy = mo_blockintegral(19)
T = mo_blockintegral(22)
mo_close()
print("Results: Fx: ",Fx, " Fy: ", Fy, " torque: ",T)

print("Moving to -0.25, -0.25")
mi_selectgroup(1)
mi_movetranslate(0, -0.25, 4)
mi_analyze()
mi_loadsolution()
mo_groupselectblock(1)
Fx = mo_blockintegral(18)
Fy = mo_blockintegral(19)
T = mo_blockintegral(22)
mo_close()
print("Results: Fx: ",Fx, " Fy: ", Fy, " torque: ",T)

print("Moving to 0.25, 0.25")
mi_selectgroup(1)
mi_movetranslate(0.5, 0.5, 4)
mi_analyze()
mi_loadsolution()
mo_groupselectblock(1)
Fx = mo_blockintegral(18)
Fy = mo_blockintegral(19)
T = mo_blockintegral(22)
mo_close()
print("Results: Fx: ",Fx, " Fy: ", Fy, " torque: ",T)

print("Moving to 0.25, 0")
mi_selectgroup(1)
mi_movetranslate(0, -0.25, 4)
mi_analyze()
mi_loadsolution()
mo_groupselectblock(1)
Fx = mo_blockintegral(18)
Fy = mo_blockintegral(19)
T = mo_blockintegral(22)
mo_close()
print("Results: Fx: ",Fx, " Fy: ", Fy, " torque: ",T)

print("Moving to 0.25, -0.25")
mi_selectgroup(1)
mi_movetranslate(0, -0.25, 4)
mi_analyze()
mi_loadsolution()
mo_groupselectblock(1)
Fx = mo_blockintegral(18)
Fy = mo_blockintegral(19)
T = mo_blockintegral(22)
mo_close()
print("Results: Fx: ",Fx, " Fy: ", Fy, " torque: ",T)

print("Returning to initial location...")
mi_selectgroup(1)
mi_movetranslate(-0.25, 0.5, 4)